language: java
branches:
  only:
  - master
before_install:
- curl --silent https://shunit2.googlecode.com/files/shunit2-2.1.6.tgz | tar xz -C
  /tmp/
- git clone https://github.com/ryanbrainard/heroku-buildpack-testrunner.git /tmp/testrunner
- "./etc/hatchet_travis_setup.sh"
install: true
script: eval $TEST_CMD
after_script: heroku keys:remove $USER@`hostname`
env:
  global:
  - HATCHET_RETRIES=3
  - HATCHET_DEPLOY_STRATEGY=git
  - HATCHET_BUILDPACK_BASE="https://github.com/heroku/heroku-buildpack-java.git"
  - SHUNIT_HOME="/tmp/shunit2-2.1.6"
  - secure: Im1SYQjYY+AiyaL9uH6X87Nw0c4gCTWtEY+ya7x3+AeKJ6HwqIB25ApMTsc1RgB94b64ZYpN5TCfjnfa6hSYiXSv+OGUuEUiaIpo4cAmSGbkk6myn67tkjKCymy+PBLqewmA9bFgqXkJzFJQ+qMtLh2Hu4JylVwQ1W8Gkpx8Nro=
  matrix:
  - TEST_CMD='[ "$TRAVIS_PULL_REQUEST" = "false" ] && mvn verify || true'
  - TEST_CMD="/tmp/testrunner/bin/run -c ."
