api = "0.2"

[buildpack]

# The v2a buildpack id is "heroku/java". This value only defines the
# v3 or Cloud Native Buildpack id.
id = "heroku/maven"

version = "0.1"
name = "Java"

  [publish.Ignore]
  files = [
    "etc/",
    "spec/",
    "test/",
    "vendor/",
    ".gitignore",
    ".github/",
    ".travis.yml",
    "circle.yml",
    "hatchet.json",
    "Gemfile",
    "Gemfile.lock"
  ]

[[stacks]]
id = "heroku-18"

# this is to allow testing of other stack compatibility and is not a guarantee
[[stacks]]
id = "io.buildpacks.stacks.bionic"
